<a href="https://colab.research.google.com/github/abin0001/Anveshion_project/blob/master/Medical_plant_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **Medicinal Plant Classification**


In [ ]:
# !nvidia-smi

In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


### **Importing Required Packages**

In [ ]:
# def module():
#Importing the Libraries.
import os  #To access file directory.
import cv2 # To handle the images.
import matplotlib.pyplot as plt # To visualise the data.
import pandas as pd # To handle the dataframesl Performance.
from ast import literal_eval # To Evaluate string  fro the arrays.
import pickle #To create a image dataset.
import numpy as np # To handle with arrays.
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input # Pretrained Model and Input processor.
from tensorflow.keras import layers, models, optimizers # For NueralNetworks
from tensorflow.keras.callbacks import TensorBoard  #To analyse the mode
from sklearn.model_selection import train_test_split #To split the data for train and d test.
from sklearn.preprocessing import LabelEncoder,StandardScaler #
from tensorflow.keras.utils import to_categorical #

### **Creating our own dataset**

In [ ]:
path = "/content/drive/MyDrive/Anveshon project/Plants Images/cropped images Resized Images"
# trg_path="/content/drive/MyDrive/Anveshon project/Plants Images"

class CreateImageDataset:
    def __init__(self, dir_path):
        # module()
        self.img_ = []
        self.label_= []
        self.dir_path = dir_path
        self.class_list = os.listdir(self.dir_path)

    def load_data(self):
        for self.class_folder in self.class_list:
            self.class_path = os.path.join(self.dir_path, self.class_folder)
            if os.path.isdir(self.class_path):
                for self.img_filename in os.listdir(self.class_path):
                    self.img_path = os.path.join(self.class_path, self.img_filename)
                    self.img = cv2.imread(self.img_path)
                    if self.img.shape != (768, 576, 3):
                      self.img = cv2.resize(self.img,(576,768))
                    else:
                      self.img = self.img
                    self.label_.append(self.class_folder)
                    self.img_.append(self.img)
        self.X=np.array(self.img_)

        return self.X,self.label_


# if __name__ == "__main__":
#     source_folder = path
#     dataset_creator = CreateImageDataset(source_folder)
#     x,y=dataset_creator.load_data()
# print(x.shape)

In [ ]:
source_folder = path
dataset_creator = CreateImageDataset(source_folder)
x,y=dataset_creator.load_data()

In [ ]:
labelencode=LabelEncoder()
y=labelencode.fit_transform(y)

In [ ]:
y

array([6, 6, 6, ..., 2, 2, 2])

In [ ]:
# y=np.array([y])

In [ ]:
# img_list=[]

# for i in range(len(x)):
#   img=x[i]
#   # print(img.shape)
#   img_list.append(img.flatten())

# img_arry=np.array(img_list)

# data=pd.DataFrame({
#     'Image':img_list,
#     'label':y
# })

# data.head()

In [ ]:
# data.info()

In [ ]:
# x=np.array(data['Image'])

In [ ]:
# img_list

In [ ]:
# img_sam=img_list[0].reshape((768, 576, 3))
# img_arr_sam=img_arry[0].reshape((768, 576, 3))

In [ ]:
# plt.imshow(img_sam)
# plt.show()
# plt.imshow(img_arr_sam)
# plt.show()

In [ ]:
x,_,y,_=train_test_split(x,y,test_size=0.9,random_state=42)

In [ ]:
x,_,y,_=train_test_split(x,y,test_size=0.9,random_state=42)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)


x_train,x_val,y_train,y_val=train_test_split(x_train,y_train,test_size=0.2,random_state=42)

In [ ]:
from keras.utils import to_categorical

y_train= to_categorical(y_train, num_classes=9)
y_val = to_categorical(y_val, num_classes=9)

In [ ]:
x_train.shape

(20, 768, 576, 3)

In [ ]:
x_test.shape

(11, 768, 576, 3)

In [ ]:
x_val.shape

(5, 768, 576, 3)

In [ ]:
# plt.rcParams["figure.figsize"] = (10,10)
# fig,axes = plt.subplots(10,10)
# for i,ax in enumerate(axes.flatten()):
#   ax.imshow(x_train[i])
#   ax.set_title(f'{y_train[i]}')
#   ax.set_xticks([])
#   ax.set_yticks([])
# fig.tight_layout()

In [ ]:
# scaler = StandardScaler()
# x_train=scaler.fit_transform(x_train)
# x_test=scaler.fit_transform(x_test)

In [ ]:
x_train=x_train/255.0

In [ ]:
# print(x_train)

In [ ]:
x_test=x_test/255.0

In [ ]:
x_val=x_val/255.0

In [ ]:
train_x_preprocessed = preprocess_input(x_train)
val_x_preprocessed = preprocess_input(x_val)

In [ ]:
train_x_preprocessed.shape

(20, 768, 576, 3)

In [ ]:
val_x_preprocessed.shape

(5, 768, 576, 3)

In [ ]:
y_train.shape

print(y_train)

[[0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]]


### **Building Vgg16 model**

In [ ]:
Vgg16_base_mdl = VGG16(weights='imagenet', include_top=False, input_shape=(x_train[0].shape),classes=9)
Vgg16_base_mdl.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 768, 576, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 768, 576, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 768, 576, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 384, 288, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 384, 288, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 384, 288, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 192, 144, 128)     0     

In [ ]:
#changing the model in to non_trainable.
for layer in Vgg16_base_mdl.layers:
    layer.trainable = False

In [ ]:
#model summary after Change non_trainable
Vgg16_base_mdl.summary()

Model: "vgg16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 768, 576, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 768, 576, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 768, 576, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 384, 288, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 384, 288, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 384, 288, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 192, 144, 128)     0     

### **Creating our Neural network**

In [ ]:
X = layers.Flatten()(Vgg16_base_mdl.output)
X = layers.Dense(256,activation='relu')(X)
X = layers.Dropout(0.5)(X)
predictions = layers.Dense(9,activation='softmax')(X)
model=models.Model(inputs=Vgg16_base_mdl.input,outputs=predictions)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(train_x_preprocessed,y_train,epochs=10,validation_data=(val_x_preprocessed,y_val))

Epoch 1/10
1/1 [==============================] - 126s 126s/step - loss: 3.4251 - accuracy: 0.1000 - val_loss: 19.4061 - val_accuracy: 0.0000e+00
Epoch 2/10
1/1 [==============================] - 140s 140s/step - loss: 20.6954 - accuracy: 0.2000 - val_loss: 19.3096 - val_accuracy: 0.0000e+00
Epoch 3/10
1/1 [==============================] - 140s 140s/step - loss: 23.8693 - accuracy: 0.1000 - val_loss: 10.2647 - val_accuracy: 0.0000e+00
Epoch 4/10
1/1 [==============================] - 137s 137s/step - loss: 17.3789 - accuracy: 0.1500 - val_loss: 6.5547 - val_accuracy: 0.2000
Epoch 5/10
1/1 [==============================] - 139s 139s/step - loss: 13.6076 - accuracy: 0.2000 - val_loss: 3.8559 - val_accuracy: 0.2000
Epoch 6/10
1/1 [==============================] - 138s 138s/step - loss: 12.0674 - accuracy: 0.1500 - val_loss: 3.7968 - val_accuracy: 0.2000
Epoch 7/10
1/1 [==============================] - 121s 121s/step - loss: 8.5790 - accuracy: 0.1000 - val_loss: 3.7957 - val_accuracy: 

In [ ]:
model.save('model.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [41]:
KERAS_MODEL_PATH = 'tf_keras_c2f.tf'

In [42]:
model.save(KERAS_MODEL_PATH, save_format='tf')

In [40]:
import tensorflow as tf

In [43]:
converter = tf.lite.TFLiteConverter.from_saved_model(KERAS_MODEL_PATH)
tflite_model = converter.convert()

# Save the TFLITE model
with open('modelc2f.tflite', 'wb') as f:
    f.write(tflite_model)

In [44]:
y_pred=model.predict(x_test)

1/1 [==============================] - 60s 60s/step


In [45]:
y_test

array([6, 8, 5, 7, 4, 3, 7, 2, 7, 4, 1])

In [46]:
y_pred

array([[6.5613375e-03, 7.2392452e-01, 1.0669976e-03, 2.7330578e-03,
        3.4715398e-04, 5.7461131e-03, 1.0525974e-03, 2.5633082e-01,
        2.2372771e-03],
       [1.2756873e-02, 6.9391614e-01, 2.7782014e-03, 3.8121317e-03,
        9.1168453e-04, 9.3949093e-03, 2.4287894e-03, 2.7055115e-01,
        3.4499965e-03],
       [9.9177174e-03, 7.0803130e-01, 3.8819911e-03, 6.3894140e-03,
        1.4291478e-03, 1.5745172e-02, 4.1584643e-03, 2.4491586e-01,
        5.5309539e-03],
       [5.9166215e-03, 6.7749679e-01, 9.4959402e-04, 2.3455522e-03,
        4.1240282e-04, 3.5946188e-03, 9.7494101e-04, 3.0652848e-01,
        1.7808912e-03],
       [7.0814150e-03, 5.5693591e-01, 1.3585713e-03, 2.2833683e-03,
        5.3915841e-04, 5.4947236e-03, 1.1372131e-03, 4.2316538e-01,
        2.0041415e-03],
       [1.1913427e-02, 7.4215901e-01, 4.0325169e-03, 4.2332420e-03,
        1.3073264e-03, 1.2640350e-02, 3.8435161e-03, 2.1337879e-01,
        6.4918343e-03],
       [9.9967131e-03, 7.3222595e-01, 2.

In [54]:
np.argmax(y_pred,axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])